title: charlesrocket
description: homepage
url: https://charlesrocket.github.io
logo: fireball.gif
locale: en_US
giscus_repo_id: MDEwOlJlcG9zaXRvcnkxNDE1MDQ2MzE=

home_title: -k
home_subtitle: x
background:
  homepage: assets/images/c1tyh4ll.png                      
  post-list: assets/images/bk-prk.jpg
  default-post: assets/images/bk-prk.jpg

permalink:          /:categories/:title
lsi:                false
safe:               true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  math_engine:        mathjax
  enable_coderay:     false
  syntax_highlighter: rouge
sass:
  sass_dir:         assets/_sass
  style:            compressed

#email:
mastodon:          charlesrocket
twitter:           charlesrocket
facebook:          charlesrocket
github:            charlesrocket
stackoverflow:     9899362/charlie137
linkedin:          charlesrocket
instagram:         charlesrocket
lastfm:            charlesrocket
reddit:            charlesrocket
flickr:            charlesrocket
keybase:           charlesrocket
#xmpp:              charlie137@jabber.calyxinstitute.org
hackernews:        charlesrocket
#behance:           charlesrocket

plugins:
  - jekyll-content-security-policy-generator
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions

safe: true
whitelist:
  - jekyll-content-security-policy-generator
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com

include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
