# Site
title: K O
description: x
url: https://charlesrocket.github.io
logo: fireball.gif
locale: en_US

# Left Block Images
background:
  homepage: images/c1tyh4ll.jpg                      # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg            # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-10.jpg # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:categories/:title
lsi:                false
safe:               true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  math_engine:        mathjax
  enable_coderay:     false
  syntax_highlighter: rouge
sass:
  sass_dir:         assets/_sass
  style:            compressed

webrick:
  headers:
    Content-Security-Policy: script-src 'self'; object-src 'none'; frame-src 'none'; base-uri 'none';
    Set-Cookie: promo_shown=1; SameSite=Lax;
    Access-Control-Allow-Origin: https://charlesrocket.github.io

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
#email:
#google.plus:       username
twitter:           charlesrocket
#facebook:          username
github:            charlesrocket
stackoverflow:     9899362/charlie137
linkedin:          charlesrocket
#xing:              username
instagram:         charlesrocket
#lastfm:            charlesrocket
#tumblr:            username
#pinterest:         username
reddit:            charlesrocket
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
flickr:            charlesrocket
#codepen:           username
#keybase:           charlesrocket
#xmpp:              username@server.com
#hackernews:        username
#behance:           charlesrocket

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
