#!/usr/bin/env bash
set -e
bundle update --bundler
bundle exec jekyll build --verbose
bundle exec htmlproofer ./_site --http-status-ignore "999" --url-swap "https?\:\/\/(127\.0\.0\.1\:4000|localhost\:4000|charlesrocket\.github.io):" --only-4xx --url-ignore "/photography" --allow-hash-href --empty-alt-ignore --assume-extension ./_site
