name: jekyll tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run tests
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install
        bundle exec jekyll build --trace --verbose
        bundle exec htmlproofer ./_site --http-status-ignore "999, 400" --url-swap "https?\:\/\/(127\.0\.0\.1\:4000|localhost\:4000|charlesrocket\.github.io):" --only-4xx --url-ignore "/photography" --allow-hash-href --empty-alt-ignore --assume-extension ./_site